version: '3.3'


services:
  postgres: 
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=mark
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes: 
      - ./postgres_data:/var/lib/postgreslq/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adminmark@mail.com
      - PGADMIN_DEFAULT_PASSWORD=mark
    ports:
      - 5050:80


  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80